[package]
name    = "doom-game"
version.workspace = true
edition.workspace = true

[features]
default = []
style_meter = []
telemetry = []
director = []
tactical_director = []

[dependencies]
doom-types = { workspace = true }
doom-map   = { workspace = true }
thiserror  = { workspace = true }
strum = { version = "0.28.0" }
strum_macros = { version = "0.28.0" }
smallvec = "1.15.1"

[dev-dependencies]
proptest = { workspace = true }
