[package]
name = "doom-types-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.doom-types]
path = "../crates/doom-types"

[dependencies.doom-wad]
path = "../crates/doom-wad"

[[bin]]
name = "fuzz_target_1"
path = "fuzz_targets/fuzz_target_1.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_3"
path = "fuzz_targets/fuzz_target_3.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_2"
path = "fuzz_targets/fuzz_target_2.rs"
test = false
doc = false
bench = false

[dependencies.doom-game]
path = "../crates/doom-game"

[[bin]]
name = "dehacked"
path = "fuzz_targets/dehacked.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_4"
path = "fuzz_targets/fuzz_target_4.rs"
test = false
doc = false
bench = false

[dependencies.doom-audio]
path = "../crates/doom-audio"

[[bin]]
name = "fuzz_target_5"
path = "fuzz_targets/fuzz_target_5.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_6"
path = "fuzz_targets/fuzz_target_6.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_15"
path = "fuzz_targets/fuzz_target_15.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_oom"
path = "fuzz_targets/fuzz_target_oom.rs"
test = false
doc = false
bench = false

[dependencies.doom-map]
path = "../crates/doom-map"

[[bin]]
name = "fuzz_target_savegame"
path = "fuzz_targets/fuzz_target_savegame.rs"
test = false
doc = false
bench = false


[[bin]]
name = "fuzz_target_analyzer"
path = "fuzz_targets/fuzz_target_analyzer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_savegame_doomrs"
path = "fuzz_targets/fuzz_target_savegame_doomrs.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_cheats"
path = "fuzz_targets/fuzz_target_cheats.rs"
test = false
doc = false
bench = false

[dependencies.doom-app]
path = "../crates/doom-app"

[[bin]]
name = "fuzz_udmf"
path = "fuzz_targets/fuzz_udmf.rs"
test = false
doc = false
bench = false
