[package]
name = "doom-types-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.doom-types]
path = "../crates/doom-types"

[dependencies.doom-wad]
path = "../crates/doom-wad"

[[bin]]
name = "fuzz_target_1"
path = "fuzz_targets/fuzz_target_1.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_3"
path = "fuzz_targets/fuzz_target_3.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_2"
path = "fuzz_targets/fuzz_target_2.rs"
test = false
doc = false
bench = false

[dependencies.doom-game]
path = "../crates/doom-game"

[[bin]]
name = "dehacked"
path = "fuzz_targets/dehacked.rs"
test = false
doc = false
bench = false
