[package]
name    = "doom-map"
version.workspace = true
edition.workspace = true

[dependencies]
doom-types = { workspace = true }
doom-wad   = { workspace = true }
thiserror  = { workspace = true }
nom        = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[features]
analyze_sight = []
