[package]
name    = "doom-app"
version.workspace = true
edition.workspace = true

[[bin]]
name = "doom-app"
path = "src/main.rs"

[dependencies]
ratatui = { workspace = true }
crossterm = { workspace = true }
doom-types    = { workspace = true }
doom-wad      = { workspace = true }
doom-map      = { workspace = true }
doom-game     = { workspace = true }
doom-renderer = { workspace = true }
doom-tui      = { workspace = true }
doom-audio    = { workspace = true }
doom-net      = { workspace = true }
doom-demo     = { workspace = true }
clap          = { workspace = true }
anyhow        = { workspace = true }
tokio         = { workspace = true }
thiserror     = { workspace = true }
loom          = { version = "0.7", optional = true }
log = "0.4.29"
comfy-table = "7.2.2"

[dev-dependencies]
loom = "0.7"

[features]
loom = ["dep:loom", "doom-audio/loom"]
